### ISSUE TITLE
Terminal colors not working on each environment

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#73]
In the ERROR message output the as well as the --help output there is some formatted text (color and style). This is done in a manner that does not work on every OS / Terminal Emulator.

The printed text "\u001b[0m\u001b[31mERROR\u001b[0m" may often appear exactly as is, instead of the red "ERROR" label that was intended to display.

The printed text in the --help output to make the name of the project bold "\033[1m{project}\033[0m" is also not safe for every environment.

This code for these can be found in `skelebot/skelebot.py` and `skelebot/common.py` respectively.

In order to support multiple OS and Terminals the colorama package could be used: https://www.geeksforgeeks.org/print-colors-python-terminal/

Test cases will need to be updated in a manner that is also system independent.
This fix should only be a patch version bump.

---

**Acceptance Criteria**
- [x] Terminal Colors are now printed in a system agnostic fashion
- [ ] Test Cases Updated for new Code
- [x] Changelog Updated
- [x] Patch Version Bumped

**Comment by sgaist** [comment]
Hi,

I'd like to take a shot a that one.

**Comment by sshookman** [comment]
Absolutely!

I can assign it to you. Just let me know if you have any questions.

Thanks for contributing!

*~ Sean Shookman ~*
*Orland Park, **Illinois,*
*United States of America, **Earth,*
*Perseus Arm, **Milky Way Galaxy,*
*Local Group, **Virgo Supercluster,*
*Observable Universe*

**Comment by vgerak** [comment]
My apologies, the issue had not been assigned when I started to work on it - it's cool if you reject the pull request in favor of @sgaist's one.

**Comment by sshookman** [comment]
@vgerak, Thank you so much for contributing, but we do ask that you announce your work in our Contributing doc: https://github.com/carsdotcom/skelebot/blob/master/CONTRIBUTING.md.

Since the build is failing anyway (my fault), I'll let @sgaist have a shot at it first.

FYI - With regards to the failing build, I forgot to mention that when adding new dependencies they also need to be added to the CircliCI config in ".circleci/config.yml" for the automated build. This was my mistake, I forgot about it and should have mentioned it in the Issue, but It does mean I can raise a new issue to avoid this annoyance in the future.

**Comment by sshookman** [comment]
Also, as a sort of Public Service announcement:

If you are trying to get credit for Hacktoberfest, only PRs opened during the month of October will be counted.

**Comment by sgaist** [comment]
Thanks !

Hacktoberfest is indeed one of the motivation :-)

Now back to our normal development schedule !

What is the minimal version of Python that you would like to support ? Depending on that, we could make some use of the new f string.

**Comment by sshookman** [comment]
It should at least support 3.6, but if it's possible to support earlier versions of 3 as well that would be great. no need to support python 2.

Thanks!

**Comment by sshookman** [comment]
You're awesome @sgaist! Thank you so much for contributing!
