### ISSUE TITLE
R and Python combined project support

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#74]
**Problem**
Some projects make use of R and Python together. Skelebot should be able to support this type of project as well.

**Suggested Solution**
Due to the fact that Python 3 is installed in the base R image, the R Docker Images should be sufficient for both R and Python.

The simplest change is in the Scaffolding process to allow for another option when selecting the project's language: "R+Python". This should in turn make use of the same images as the "R" language projects since that image already has Python 3 installed.

The main thing that needs to be updated is the dependency list. Currently this interprets the dependencies as entirely R or entirely Python depending on the selected language of the project. For a multi-language project we would need another way to define the language of the dependency. This could be done with a simple prefix such as "python::" or "R::", but alternatives methods to distinguish language should also be considered.

**Alternative**
If during testing, the current R images are not sufficient, another base image may need to be created specifically for this purpose. If so, I would advise looking into Anaconda as a solution since it can handle R and Python quite well.

---

**Acceptance Criteria**
- [x] New Language Option: "R+Python"
- [x] Must be able to install both R and Python dependencies via Skelebot
- [x] Must be able to execute both .R and .py scripts via Skelebot Jobs
- [x] All existing functionality remains unchanged (to remain on v1)
- [x] New test cases covering the new added/updated code and all edge cases
- [x] Updated Changelog and GitHub Pages Docs
- [x] Minor version bumped

**Comment by chutchi2** [comment]
I think I have what it takes to take this on. Could you assign this to me and I can take a crack at it?

**Comment by sshookman** [comment]
Absolutely @chutchi2!

This one may be a bit tricky, so feel free to reach out if you have any questions.

Thanks!

**Comment by chutchi2** [comment]
I look forward to it!

**Comment by chutchi2** [comment]
@sshookman I am trying to push to this repo (sorry for the delay!) but I dont believe I have push access. Perhaps I'm doing something wrong, but could you check my access rights?

**Comment by sshookman** [comment]
@chutchi2 You don't need to push, just open a Pull Request (you should see a button for that on your forked repo). Once you open the Pull Request we can review it, work on it (if needed), and hopefully get it merged real soon.

**Comment by sshookman** [comment]
Thank you again @chutchi2 for your awesome contribution to Skelebot!
