### ISSUE TITLE
Single Source of Truth for Dependencies

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#76]
**Problem**
The dependencies for the project are laid out in the setup.py as well as the .circleci/config.yml file. This is annoying since it means you have to specify dependency changes in two different places.

**Suggested Solution**
We could use a requirements.txt that can be used in both locations to keep the list of dependencies in a single location.

This does not solve the problem where we also have the dependencies in the skelebot.yaml file, but that can be solved separately.

---

**Acceptance Criteria**
- [x] Single source of truth for dependencies that setup.py and circleci config both utilize
- [x] Update Changelog
- [x] Bump patch version

**Comment by kislam01** [comment]
Hello! I would like to take a shot at this. Could I please be assigned the issue? Thank you!

**Comment by sshookman** [comment]
It's all yours @kislam01!

Thanks for contributing. Be sure to reach out if you have any questions.

**Comment by sshookman** [comment]
Thank you so much for contributing to this project, @kislam01!
