### ISSUE TITLE
Custom Commands in Generated Dockerfile

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#77]
**Problem**
It is often necessary to add custom RUN commands into a Dockerfile, and currently Skelebot does not allow you to do that.

**Suggested Solution**
Add a new property called “commands" to the skelebot config (skelebot.yaml) where users can specify any commands they want to run. These commands should be added into the Skelebot generated Dockerfile directly after the dependency installations.

```
commands:
- python setup.py clean --all install
- rm -rf build/
- rm -rf dist/
```

---

**Acceptance Criteria**
- [ ] New "commands" property added to the root of the config
- [ ] "commands" property is optional
- [ ] "commands" property expects a list of strings
- [ ] Commands in the "commands" property are added to the generated Dockerfile
- [ ] Commands are only added AFTER the dependency installs
- [ ] Test Cases Updated for new Code
- [ ] Changelog and GitHub Docs Updated to feature the new "commands" parameter
- [ ] Minor Version Bumped

**Comment by jagmoreira** [comment]
I'll take a stab at this one.

**Comment by sshookman** [comment]
Indeed, Sir.
