### ISSUE TITLE
Allow Simple Commands for Jobs to Execute

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#78]
**Problem**
Currently jobs can only execute a script: (".py", ".sh", or ".R") with the "source" property in the skelebot.yaml file. There are use cases where someone may want to simply run a single command instead.

**Suggested Solution**
Allow Skelebot to identify job sources where no extension is provided and simply run the command "as is". Meaning, this will not prefix the source with "Rscript" or "python -u", but instead just run the source as it is.

```
jobs:
- name: hello
  source: echo 'HELLO'
  help: Say Hello
```

**Warning**
Right now the "source" property expects a single script, which means it expects a single "word" (no spaces, such as 'my-jobs/run.py'). With commands available for use in the source property, this could change (as seen above with an echo command).

Determining this is a command not a script should probably be based on the first word in the string.

For Example: 

This source would be a command: echo.
```
source: echo 'HELLO'
```

But this source would still be a script and therefore require the "python -u" prefix upon execution.
```
source: echo.py 'HELLO'
```

---

**Acceptance Criteria**
- [x] The "source" property allows for the execution of commands directly
- [x] The "source" property still allows for the execution of scripts (python, bash, or R)
- [x] Test Cases Updated for new Code
- [x] Changelog and GitHub Docs Updated
- [x] Minor Version Bumped

**Comment by SanthoshBala18** [comment]
I would like to work on this feature.

**Comment by sshookman** [comment]
Thank you so much for contributing, @SanthoshBala18 !

I'll assign this to you.

**Comment by sshookman** [comment]
Congratulations, @SanthoshBala18 on being the first Code Contributor to Skelebot (aside from lonely old me)!

Thank you, again!

**Comment by SanthoshBala18** [comment]
Wow nice to know that I am the first contributor ;) would love to contribute more in the future.. !

**Comment by sshookman** [comment]
That would be awesome, @SanthoshBala18 ! You write quality code. Your contributions are always welcome!
