### ISSUE TITLE
Report and Quarantine Hazardous Plugins

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#90]
## Problem
Currently if you install a Skelebot plugin that contains a code error all of Skelebot will crash whenever any command is run because the bad code is being loaded and fails.

## Solution
During the loading of plugins it would be ideal to catch any of these errors (try/except), report the bad plugin to the end-user (print), and quarantine the plugin in a separate folder (~/.skelebot/quarantined-plugins/) to prevent the bad plugin from crashing Skelebot entirely.

If the `~/.skelebot/quarantined-plugins/` folder does not exist, it should be created when it is needed.

Suggested Message:
`WARNING | The '{plugin-name}' plugin contains errors - Adding plugin to Quarantine`

Colorama can be used to color the `WARNING` text orange similar to how `ERROR` is colored red.

## Acceptance Criteria
- [x] Broken plugins being installed does not cause Skelebot to crash
- [x] Broken plugins are reported with yellow "WARNING" prefix using colorama
- [x] Broken plugins are moved to the quarantine folder so they no longer execute
- [x] Test Cases Added and Updated
- [x] Patch Version Bumped
- [x] Changelog Updated

**Comment by dubesar** [comment]
Hey, I understood the issue, Can I work on this issue?

**Comment by sshookman** [comment]
Absolutely, @dubesar!
Thank you!

**Comment by sshookman** [comment]
@dubesar, please let me know if you still intend to work on this issue. If I don't hear from you by the end of the week I'll assume that you are no longer interested.

Thanks
