### ISSUE TITLE
Append Env Name to Image Name

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#94]
**Problem**
The name of the image is the same, even when you pass the `--env` parameter to Skelebot to specify a different configuration. This results in the `--env` image overriding any previous image. This is a concern when you want to allow for a project to build multiple images based on different configs.

**Solution**
When a user passes the `--env` flag and an env config is loaded, the name of the env should be appended to the name of the image so as to make a new image, and not replace the previous image.

---

**Acceptance Criteria**
- [x] Building images **with** `--env` should create image names that include the name of the env
- [x] Building image **without** `--env` should not append anything to the image name
- [x] Add or Update Unit Tests as Needed
- [x] Bump Minor Version
- [x] Update Changelog

**Comment by jagmoreira** [comment]
I'll take care of it
