### ISSUE TITLE
Allow Python Dependencies from GitHub and Project Folder

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#97]
**Problem**
Currently the only way to get Python packages installed through Skelebot is via `pip install`. If you would like to install a package from source that is contained in your project, or from source on GitHub, this is currently not possible (or at least, not easy).

**Solution**
Skelebot should support installing Python packages from source located in the project folder as well as on GitHub, much in the same way that Skelebot allows R dependencies to be installed.

In the dependencies list in the skelebot.yaml file, the following entry would specify the source folder location for the package, and the name of the package being installed.

`- file:/libs/my-ds-lib/:ds-lib`

This entry in the dependencies list would install a Python package from a GitHub repo with the given name.

`- github:https://github.com/carsdotcom/ds-lib:ds-lib`

---

**Acceptance Criteria**
- [x] Allow Python dependencies to be installed from source code inside the project
- [x] Allow Python dependencies to be installed from source code in a GitHub repo
- [x] Add or update unit tests to cover the new code
- [x] Update Changelog and GitHub Pages Docs
- [x] Bump Minor Version

**Comment by sherry0531** [comment]
assign to me

**Comment by sshookman** [comment]
Assigned!
